name: MajoranaAlgebras
version: "1.5.2"
license: "GPL-2.0-or-later"
date: 2024-07-07
description: |
    A package for constructing Majorana algebras and representations

authors:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/
    - name: Madeleine Whybrow
      url: https://madeleinewhybrow.wordpress.com

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "automata"
      version: ">= 1.13"
      url: "https://gap-packages.github.io/automata/"
    - name: "Gauss"
      version: ">=0"
      url: "https://homalg-project.github.io/pkg/Gauss"
    - name: "datastructures"
      version: ">=0.2.2"
      url: "https://gap-packages.github.io/datastructures"

suggested-pkgs:
    - name: "Char0Gauss"
      version: ">=0"

www: https://gap-packages.github.io/MajoranaAlgebras/
readme: README.md
packageinfo: https://gap-packages.github.io/MajoranaAlgebras/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/MajoranaAlgebras/releases/download/v1.5.2/MajoranaAlgebras-1.5.2.tar.gz

abstract: |
    MajoranaAlgebras is a package for constructing Majorana
    representations of finite groups. It also offers some functions to calculate
    with a constructed Majorana representation. The main constructive functions
    use the algorithm described in the preprint Constructing Majorana
    Representations (https://arxiv.org/abs/1803.10723) by Markus Pfeiffer and
    Madeleine Whybrow.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Majorana algebras, axial algebras.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PWT24</span>]   <b class='BibAuthor'>Pfeiffer, M., Whybrow, M. and GAP Team, T.</b>,
     <i class='BibTitle'>MajoranaAlgebras, A package for constructing Majorana algebras and representations,
             Version 1.5.2</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/MajoranaAlgebras/">https://gap-packages.github.io/MajoranaAlgebras/</a></span>.
    </p>
    

bibtex: |
    @misc{ MajoranaAlgebras,
      author =           {Pfeiffer, M. and Whybrow, M. and GAP Team, T.},
      title =            {{MajoranaAlgebras},   A   package   for   constructing
                          Majorana algebras and representations, {V}ersion 1.5.2},
      month =            {Jul},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href
                          {https://gap-packages.github.io/MajoranaAlgebras/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{MajoranaAlgebras/}}},
      keywords =         {Majorana algebras; axial algebras},
      printedkey =       {PWT24}
    }

